export const events = [
  {
    _id: '622b3c4b27c135009e310b27',
    name: 'It has survived not only five centuries',
    text: "Какой-то текст задачи, например, Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean imperdiet consectetur dolor, nec consectetur nisl mattis ut. Proin ac sapien at elit lacinia semper. Nullam vestibulum rutrum efficitur. Sed et egestas ante, id ullamcorper ante. Maecenas porta sem ultrices libero tempus, eu laoreet turpis bibendum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed laoreet est et nisi tristique, ut hendrerit tellus pulvinar. Proin eget elit a mauris convallis molestie nec vel nisi. Etiam accumsan porta velit et convallis. Maecenas euismod scelerisque lectus, non varius velit condimentum non. Vestibulum luctus risus et metus volutpat, at sodales massa gravida",
    autor: 'onegin',
    date: '2022-03-18T20:36:38.407Z',
    type: "error",
    status: "ready",
    priority: "low",
  },
  {
    _id: '622b3c4b27cb27',
    name: 'It has survived not only five centuries',
    autor: 'Pushkin',
    date: '2022-03-18T20:36:38.407Z',
    type: "done",
    status: "inwork",
    priority: "hight",
  },
  {
    _id: '622b3c5009e310b27',
    name: 'It has survived not only five centuries',
    autor: 'onegin',
    text: "Какой-то текст задачи, например, Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean imperdiet consectetur dolor, nec consectetur nisl mattis ut. Proin ac sapien at elit lacinia semper. Nullam vestibulum rutrum efficitur. Sed et egestas ante, id ullamcorper ante. Maecenas porta sem ultrices libero tempus, eu laoreet turpis bibendum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed laoreet est et nisi tristique, ut hendrerit tellus pulvinar. Proin eget elit a mauris convallis molestie nec vel nisi. Etiam accumsan porta velit et convallis. Maecenas euismod scelerisque lectus, non varius velit condimentum non. Vestibulum luctus risus et metus volutpat, at sodales massa gravida",
    date: '2022-03-18T20:36:38.407Z',
    type: "error",
    status: "ready",
    priority: "low",
  },
  {
    _id: '622b3c4b275009e310b27',
    name: 'It has survived not only five centuries',
    autor: 'Pushkin',
    date: '2022-03-18T20:36:38.407Z',
    type: "done",
    status: "inwork",
    priority: "hight",
  },
  {
    _id: '622b3c47c135009e310b27',
    name: 'It has survived not only five centuries',
    autor: 'onegin',
    date: '2022-03-18T20:36:38.407Z',
    type: "error",
    status: "ready",
    priority: "low",
  },
  {
    _id: '622b3c4b27c135009e31',
    name: 'It has survived not only five centuries',
    autor: 'Pushkin',
    date: '2022-03-18T20:36:38.407Z',
    type: "done",
    status: "inwork",
    priority: "hight",
  },
  {
    _id: '622b3c4b27c135009e310b',
    name: 'It has survived not only five centuries',
    autor: 'onegin',
    date: '2022-03-18T20:36:38.407Z',
    type: "error",
    status: "ready",
    priority: "low",
  },
  {
    _id: '622b3c4b27c1350',
    name: 'It has survived not only five centuries',
    autor: 'Pushkin',
    date: '2022-03-18T20:36:38.407Z',
    type: "done",
    status: "inwork",
    priority: "hight",
  }
]
